horizontal_tile_number = 27
vertical_tile_number = 30
tile_size = 16
game_screen_height = vertical_tile_number * tile_size
game_screen_width = horizontal_tile_number * tile_size
target_fps = -1
max_delta_time = 3
ghost_tiles_to_follow = 10
window_scale = 1.5
tracker_width = 200
webcam_id = 1
use_tracking = True
